[profile.default]
src = "src"
out = "out"
libs = ["node_modules"]
via_ir = true
optimizer = true
optimizer_runs = 20000
gas_reports = ["*"]

remappings = [
    "@interfaces/=src/interfaces/",
    "@models/=src/models/",
    "@openzeppelin/=node_modules/@openzeppelin/",
    "@cartesi/=node_modules/@cartesi/"
]
