[profile.default]
src = "src"
out = "out"
libs = ["node_modules", "lib"]
via_ir = true
optimizer = true
optimizer_runs = 20000

remappings = [
    "@std=lib/forge-std/src/",
    "@interfaces/=src/interfaces/",
    "@models/=src/models/",
    "@openzeppelin/=node_modules/@openzeppelin/",
    "@cartesi/=node_modules/@cartesi/"
]
