// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

import { CartridgeInsertionModelData } from "../tables/CartridgeInsertionModel.sol";
import { TapeSubmissionModelData } from "../tables/TapeSubmissionModel.sol";

/**
 * @title ICoreSystem
 * @author MUD (https://mud.dev) by Lattice (https://lattice.xyz)
 * @dev This interface is automatically generated from the corresponding system contract. Do not edit manually.
 */
interface ICoreSystem {
  error CoreSystem__NotPermited();
  error CoreSystem__InvalidParams();
  error CoreSystem__InvalidModel();

  function core__getCartridgeOwner(bytes32 cartridgeId) external view returns (address);

  function core__setCartridgeOwner(bytes32 cartridgeId, address newOwner) external;

  function core__getTapeCreator(bytes32 tapeId) external view returns (address);

  function core__getCartridgeInsertionModel() external view returns (CartridgeInsertionModelData memory);

  function core__setTapeSubmissionModel(bytes32 cartridgeId, address modelAddress, bytes calldata config) external;

  function core__getTapeSubmissionModel(bytes32 cartridgeId) external view returns (TapeSubmissionModelData memory);

  function core__getCartridgeIdFromTapeId(bytes calldata payload) external pure returns (bytes32);

  function core__getTapeSubmissionModelAddress(bytes32 tapeOrCartridgeId) external view returns (address);

  function core__getSystem(bytes16 systemName) external view returns (address);

  function core__getRegisteredModel(address modelAddress) external view returns (bool);

  function core__setDappAddress(address _dapp) external;
}
