// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

/**
 * @title IInputBoxSystem
 * @author MUD (https://mud.dev) by Lattice (https://lattice.xyz)
 * @dev This interface is automatically generated from the corresponding system contract. Do not edit manually.
 */
interface IInputBoxSystem {
  error InputBoxSystem__NoInputBox();

  function core__proxyAddInput(address _dapp, bytes calldata _payload) external returns (bytes32);
}
