// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

import { InputBoxAddress } from "./tables/InputBoxAddress.sol";
import { DappAddressNamespace } from "./tables/DappAddressNamespace.sol";
import { NamespaceDappAddress } from "./tables/NamespaceDappAddress.sol";
import { CartridgeAssetAddress } from "./tables/CartridgeAssetAddress.sol";
import { CartridgeOwner } from "./tables/CartridgeOwner.sol";
import { TapeAssetAddress } from "./tables/TapeAssetAddress.sol";
import { TapeCreator } from "./tables/TapeCreator.sol";
import { RegisteredModel } from "./tables/RegisteredModel.sol";
import { CartridgeInsertionModel, CartridgeInsertionModelData } from "./tables/CartridgeInsertionModel.sol";
import { TapeSubmissionModel, TapeSubmissionModelData } from "./tables/TapeSubmissionModel.sol";
import { DappMessagesDebug, DappMessagesDebugData } from "./tables/DappMessagesDebug.sol";
import { DebugCounter } from "./tables/DebugCounter.sol";
